// Code generated by github.com/skyorm/skygen. DO NOT EDIT.
package models

import (
	"github.com/skyorm/skyorm"
)

var (
	// MStore represents skyorm.Store for M struct.
	MStore = skyorm.NewStore(
		"some_table_name",
		0,
		func() skyorm.Model { return new(M) },
		skyorm.NewProp("id", "string", true),
		skyorm.NewProp("string_value", "string", false),
		skyorm.NewProp("uint_value", "uint64", false),
	)
)

// OrmStore implements skyorm.Store interface.
func (m *M) OrmStore() skyorm.Store {
	return MStore
}

// OrmPk implements skyorm.Store interface.
func (m *M) OrmPk() interface{} {
	return m.ID
}

// OrmPkPointer implements skyorm.Store interface.
func (m *M) OrmPkPointer() interface{} {
	return &m.ID
}

// OrmPkProp implements skyorm.Store interface.
func (m *M) OrmPkProp() skyorm.Prop {
	return MStore.Pk()
}

// OrmProps implements skyorm.Store interface.
func (m *M) OrmProps() []skyorm.Prop {
	return MStore.Props()
}

// OrmPointers implements skyorm.Store interface.
func (m *M) OrmPointers() []interface{} {
	return []interface{}{
		&m.ID,
		&m.Value,
		&m.UintValue,
	}
}

// OrmVals implements skyorm.Store interface.
func (m *M) OrmVals() []interface{} {
	return []interface{}{
		m.ID,
		m.Value,
		m.UintValue,
	}
}

// IDProp returns skyorm.Prop for m.ID field.
func (m *M) IDProp() skyorm.Prop {
	return m.OrmProps()[0]
}

// ValueProp returns skyorm.Prop for m.Value field.
func (m *M) ValueProp() skyorm.Prop {
	return m.OrmProps()[1]
}

// UintValueProp returns skyorm.Prop for m.UintValue field.
func (m *M) UintValueProp() skyorm.Prop {
	return m.OrmProps()[2]
}
